language: cpp

sudo: required

os:
  - linux
  - osx

env:
  - QT_VERSION=qt4
  - QT_VERSION=qt5

install: source .travis/install.sh

script: ./.travis/script.sh

deploy:
  provider: releases
  api_key:
    secure: g7mlT2O4PfBMp5TqPKp1NEuCPrupFEEwdv3AUO0hWPYwAZ+KzV5E7NEPcRZ8tKDEVbxTDZp/+8mdt+LGh31WIEd0zzPlpMsdvKZtln5XGD0B5J8Ghti3jzrdW9fMYWCaosc9w4BCQDF+BS4qHDwv1fMCyq3R4zi3nxB2WgVgMvI=
  skip_cleanup: true
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/build/libneurosuite_*.deb"
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux && $QT_VERSION = qt4"
